package com.oberdiah.deepcomplexity.context

import com.oberdiah.deepcomplexity.evaluation.Expr
import com.oberdiah.deepcomplexity.evaluation.ExprToString
import com.oberdiah.deepcomplexity.staticAnalysis.CanBeCast
import com.oberdiah.deepcomplexity.staticAnalysis.HasIndicator
import com.oberdiah.deepcomplexity.staticAnalysis.Indicator
import com.oberdiah.deepcomplexity.staticAnalysis.variances.Variances
import com.oberdiah.deepcomplexity.utilities.Utilities.WONT_IMPLEMENT

/**
 * Used in constraints and evaluation.
 */
sealed interface EvaluationKey<T : Any> : CanBeCast<T> {
    fun makeVarianceRepresentingOneOf(): Variances<T> = this.ind.newVarianceRepresentingOneOf(this)

    override fun coerceToNumbers(): EvaluationKey<out Number> = super.coerceToNumbers() as EvaluationKey
    override fun coerceToObject(): EvaluationKey<HeapMarker> = super.coerceToObject() as EvaluationKey
    override fun <Q : Any> coerceTo(newInd: Indicator<Q>): EvaluationKey<Q> = super.coerceTo(newInd) as EvaluationKey
    override fun <Q : Any> castTo(newInd: Indicator<Q>): EvaluationKey<Q> = super.castTo(newInd) as EvaluationKey

    override fun <Q : Any> tryCastTo(newInd: Indicator<Q>): HasIndicator<Q>? {
        if (newInd == ind) {
            // Safety: newInd == ind.
            @Suppress("UNCHECKED_CAST")
            return this as HasIndicator<Q>?
        }
        WONT_IMPLEMENT("I'm not sure there's a way to cast Evaluation Keys")
    }

    /**
     * Used to allow us to equate expressions.
     */
    data class ExpressionKey<T : Any>(val expr: Expr<T>) : EvaluationKey<T> {
        override val ind: Indicator<T>
            get() = expr.ind

        override fun toString(): String = ExprToString.toExprKeyString(expr)
    }

    /**
     * Purely used to represent the constant value in a NumberVariance
     */
    object ConstantKey : EvaluationKey<Nothing> {
        override val ind: Indicator<Nothing>
            get() = throw IllegalStateException("Constant keys don't have a type.")

        override fun toString(): String = "C"
    }

    fun isAutogenerated(): Boolean = isConstant() || isExpr()
    fun isConstant(): Boolean = this is ConstantKey
    fun isExpr(): Boolean = this is ExpressionKey

    /**
     * When multiplying, we need to decide which one gets to live on.
     */
    fun importance(): Int {
        return when (this) {
            is VariableKey -> 3
            is ExpressionKey -> 2
            is LoopKey<*> -> 1
            is ConstantKey -> 0
        }
    }
}