package com.oberdiah.deepcomplexity.context

import com.oberdiah.deepcomplexity.evaluation.Expr
import com.oberdiah.deepcomplexity.evaluation.ExprToString
import com.oberdiah.deepcomplexity.staticAnalysis.HasIndicator
import com.oberdiah.deepcomplexity.staticAnalysis.Indicator

/**
 * Used in constraints and evaluation.
 */
sealed interface EvaluationKey<T : Any> : HasIndicator<T> {
    /**
     * Used to allow us to equate expressions.
     */
    data class ExpressionKey<T : Any>(val expr: Expr<T>) : EvaluationKey<T> {
        override val ind: Indicator<T>
            get() = expr.ind

        override fun toString(): String = ExprToString.toExprKeyString(expr)
    }

    /**
     * Purely used to represent the constant value in a NumberVariance
     */
    object ConstantKey : EvaluationKey<Nothing> {
        override val ind: Indicator<Nothing>
            get() = throw IllegalStateException("Constant keys don't have a type.")

        override fun toString(): String = "C"
    }

    fun isAutogenerated(): Boolean = isConstant() || isExpr()
    fun isConstant(): Boolean = this is ConstantKey
    fun isExpr(): Boolean = this is ExpressionKey

    /**
     * When multiplying, we need to decide which one gets to live on.
     */
    fun importance(): Int {
        return when (this) {
            is VariableKey -> 3
            is ExpressionKey -> 2
            is LoopKey<*> -> 1
            is ConstantKey -> 0
        }
    }
}