package com.oberdiah.deepcomplexity.staticAnalysis.variances

import com.oberdiah.deepcomplexity.context.EvaluationKey
import com.oberdiah.deepcomplexity.evaluation.BinaryNumberOp
import com.oberdiah.deepcomplexity.evaluation.BinaryNumberOp.*
import com.oberdiah.deepcomplexity.evaluation.ComparisonOp
import com.oberdiah.deepcomplexity.staticAnalysis.Indicator
import com.oberdiah.deepcomplexity.staticAnalysis.LongIndicator
import com.oberdiah.deepcomplexity.staticAnalysis.NumberIndicator
import com.oberdiah.deepcomplexity.staticAnalysis.constrainedSets.Constraints
import com.oberdiah.deepcomplexity.staticAnalysis.sets.BooleanSet
import com.oberdiah.deepcomplexity.staticAnalysis.sets.NumberSet
import com.oberdiah.deepcomplexity.utilities.Functional
import com.oberdiah.deepcomplexity.utilities.into

/**
 * Think of this as a linear equation like the form: `2x + 3y + 4z + c`
 * where the keys are the variables (x, y, z) and the values are the multipliers (2, 3, 4).
 * The constant (c) is represented by the Constant key.
 *
 * Now, we don't store the constraints here; they come in from outside, so we can't calculate a full
 * range from this alone. So intuitively, when we want to collapse, we take the constraints for each key
 * and multiply them by the multiplier, and then add them all together.
 *
 * When operations are performed, both variances must have the same indicator. That's just how operations
 * work in Java. Any variance that is legal before the operation should be legal after without too much fuss.
 *
 * We're considering NumberVariances a whole-number-only zone for now, so we first cast everything into Long.
 *
 * A NumberVariances instance collapses by first turning everything into longs, then multiplying and adding over those
 * longs, and then finally squishing down into the type.
 *
 * What this means for casting (here x is an integer):
 * `(short) x`        -> A simple type swap is fine, NumberVariances<Short>(1*int) is ok.
 *                       The int comes in and becomes a `short` during collapse, no problems there.
 * `(short) 2x`       -> Fine as well. NumberVariances<Short>(2*int) also contains all the information required
 *                       for a full reconstruction.
 * `(long) x`         -> Fine too, for a similar reason. This is starting to get risky, though, as we can only do this
 *                       if the underlying equation couldn't get beyond its old bounds (int). If it could,
 *                       we could no longer do this. For example,
 * `(long) 2x`        -> Must be collapsed. Converting this naively to NumberVariances<Long>(2*int) would change its
 *                       meaning.
 * `(int) ((byte) x)` -> Big problem, must be collapsed. Can't possibly be represented.
 *
 * In summary, if the underlying equation could get beyond the bounds we previously had it under, and we're
 * growing in size, we must collapse.
 */
@ConsistentCopyVisibility
data class NumberVariances<T : Number> private constructor(
    override val ind: NumberIndicator<T>,
    /**
     * The indicator of the key is important; it lets us know the underlying constraints of the types we're
     * dealing with.
     */
    private val multipliers: Map<EvaluationKey, NumberSet<Long>> = mapOf()
) : Variances<T> {
    init {
        require(multipliers.size < 10) {
            "Too many multipliers in NumberVariances: ${multipliers.size}. " +
                    "This isn't a hard limit, but it's questionable from a performance perspective."
        }
    }

    override fun toString(): String {
        return multipliers.entries.joinToString(", ") { (key, multiplier) ->
            "$key: ($multiplier)"
        }
    }

    companion object {
        fun <T : Number> newFromConstant(constant: NumberSet<T>): NumberVariances<T> =
            NumberVariances(constant.ind, mapOf(EvaluationKey.ConstantKey to constant.castTo(LongIndicator).into()))

        fun <T : Number> newFromVariance(ind: NumberIndicator<T>, key: EvaluationKey): NumberVariances<T> =
            NumberVariances(ind, mapOf(key to LongIndicator.onlyOneSet()))
    }

    override fun toDebugString(constraints: Constraints): String {
        return if (varsTracking().isEmpty()) {
            multipliers[EvaluationKey.ConstantKey]?.toString() ?: "0"
        } else {
            multipliers.entries.filter { (k, m) -> !(m.isZero() && k.isAutogenerated()) }
                .joinToString(" + ") { (key, multiplier) ->
                    val multiplierStr = if (multiplier.isOne() && !key.isConstant()) "" else "$multiplier"
                    val keyStr = if (key.isConstant()) "" else key.toString()
                    val constraint = grabConstraint(constraints, key)
                    val constraintStr = if (constraint.isFull()) "" else "[$constraint]"

                    "$multiplierStr$keyStr$constraintStr"
                }
        }
    }

    override fun varsTracking(): Collection<EvaluationKey> {
        return multipliers.keys.filter { !it.isConstant() }
    }

    fun grabConstraint(constraints: Constraints, key: EvaluationKey): NumberSet<Long> {
        return if (key.isConstant()) {
            // Constants don't have any variance or constraints,
            // so the 'variable', if you can call it that, is always constrained to exactly 1.
            LongIndicator.onlyOneSet()
        } else {
            constraints.getConstraint(key).castTo(LongIndicator).into()
        }
    }

    /**
     * Collapse the multipliers into a single set of values.
     * Requires constraints because a NumberVariance on its own doesn't contain
     * all the information it needs alone.
     */
    override fun collapse(constraints: Constraints): NumberSet<T> =
        collapseWithoutLimits(constraints).castTo(ind).into()

    private fun collapseWithoutLimits(constraints: Constraints): NumberSet<Long> =
        multipliers.entries.fold(LongIndicator.onlyZeroSet()) { acc, (key, multiplier) ->
            acc.add(multiplier.multiply(grabConstraint(constraints, key)))
        }

    override fun <Q : Any> attemptHardCastTo(
        newInd: Indicator<Q>,
        constraints: Constraints
    ): Variances<Q>? {
        if (newInd !is NumberIndicator<*>) {
            return null
        }
        if (newInd == ind) {
            // Safety: newInd == ind.
            @Suppress("UNCHECKED_CAST")
            return this as Variances<Q>
        }

        fun <OutT : Number> extra(newInd: NumberIndicator<OutT>): NumberVariances<OutT>? {
            if (ind.canSafelyContain(newInd)) {
                // If we've shrunken down, we don't need to do anything, and we can continue as-is.
                return NumberVariances(newInd, multipliers)
            } else {
                // Ok, so we're being asked to grow (e.g. from a short to an int)

                // Was it possible that our previous setup could overflow?
                val totalRange = collapseWithoutLimits(constraints).getRange()
                val indRange = ind.getTotalRange()
                if (indRange.contains(totalRange.first) && indRange.contains(totalRange.second)) {
                    // No risk of overflow, we can just do a type swap and be done with it.
                    return NumberVariances(newInd, multipliers)
                } else {
                    // Unfortunately, we have to collapse :(
                    val collapsedSet = collapse(constraints).tryCastTo(newInd)?.into() ?: return null
                    return newFromConstant(collapsedSet)
                }
            }
        }

        @Suppress("UNCHECKED_CAST") // Safety: Trivially true by checking the signature of extra().
        return extra(newInd) as Variances<Q>?
    }

    fun isOne(constraints: Constraints): Boolean = collapse(constraints).isOne()

    fun negate(): NumberVariances<T> {
        return NumberVariances(ind, multipliers.mapValues { (_, multiplier) ->
            multiplier.negate()
        })
    }

    fun arithmeticOperation(
        other: NumberVariances<T>,
        operation: BinaryNumberOp,
        constraints: Constraints
    ): NumberVariances<T> {
        when (operation) {
            ADDITION, SUBTRACTION -> {
                return NumberVariances(
                    ind, Functional.mergeMapsWithBlank(
                        multipliers,
                        other.multipliers,
                        LongIndicator.onlyZeroSet()
                    ) { mySet, otherSet ->
                        if (operation == ADDITION) {
                            mySet.add(otherSet)
                        } else {
                            mySet.subtract(otherSet)
                        }
                    })
            }

            MULTIPLICATION -> {
                val newMultipliers = mutableMapOf<EvaluationKey, NumberSet<Long>>()

                for ((key, meMultiplier) in multipliers) {
                    for ((otherKey, otherMultiplier) in other.multipliers) {
                        val meCollapsed = meMultiplier.multiply(grabConstraint(constraints, key))
                        val otherCollapsed = otherMultiplier.multiply(grabConstraint(constraints, otherKey))

                        val myImportance = key.importance()
                        val otherImportance = otherKey.importance()

                        val newMultiplier = if (myImportance >= otherImportance) {
                            meMultiplier.multiply(otherCollapsed)
                        } else {
                            otherMultiplier.multiply(meCollapsed)
                        }

                        // In regard to multiplying a key with itself, we have two choices:
                        // 1.  We want to ensure the value is positive. The variable by default
                        //     may be negative, so if we want this, we'll have to shove it into a constant,
                        //     losing tracking.
                        //     Well, that or create a brand-new system where we can track special constraints
                        //     within our keys. (Note, could be fun, not completely out the window.)
                        //     Wait, maybe we investigate that idea further, that sounds cool.
                        // 2.  We treat them as two separate keys and collapse one half.
                        //     This allows us to maintain part of the idea that we're still dependent on the variable.
                        //     So that down the road if we multiply by something else that is also dependent on the
                        //     variable, some of that information is kicking around to infer with.

                        val baseKey = if (myImportance >= otherImportance) key else otherKey

                        newMultipliers.compute(baseKey) { _, set ->
                            set?.add(newMultiplier) ?: newMultiplier
                        }
                    }
                }

                return NumberVariances(ind, newMultipliers)
            }

            DIVISION -> {
                if (other.isOne(constraints)) {
                    return this
                }

                val meCollapsed = this.collapse(constraints)
                val otherCollapsed = other.collapse(constraints)

                // I don't think we can do any better, at least for whole numbers.
                // If you imagine we have 1x, and we're dividing by 2, there's really nothing we can do in that
                // situation other than collapse.

                return newFromConstant(
                    meCollapsed.divide(otherCollapsed)
                )
            }

            MODULO, MINIMUM, MAXIMUM -> {
                // In theory, there may be some edge cases where we can retain variable tracking through
                // a minimum or maximum, but I'm not going to consider them unless they come up.
                // In the general case it's not doable as we don't have max or min features built into the variance.
                val meCollapsed = this.collapse(constraints)
                val otherCollapsed = other.collapse(constraints)

                return newFromConstant(
                    meCollapsed.arithmeticOperation(otherCollapsed, operation)
                )
            }
        }
    }

    /**
     * Calculates the change that a variable named key, assigned to this variance
     * in a loop, would experience on each step of that loop.
     *
     * For example, using `x`, the variance `x + 2y + 2` constrained to y: [3..5] would have
     * a change per step of 2 * [3..5] + 2 = [8..12].
     *
     * A variance that tracks x more than once e.g. `2x + 4` or tracks it negatively e.g. `-x + 3` can't be
     * solved for a change per step and will return null.
     */
    fun calculateChangePerStep(key: EvaluationKey, constraints: Constraints): NumberVariances<T>? {
        val multiplier = multipliers[key] ?: ind.onlyZeroSet()

        if (multiplier.isZero()) {
            // Returning zero may be correct here, but I want to investigate closer later.
            // Return null for now.
            return null
        }

        if (multiplier.isOne()) {
            return newFromConstant(
                NumberVariances(ind, multipliers.filter { it.key != key }).collapse(constraints)
            )
        }

        return null
    }

    /**
     * Given a comparison e.g. 3x + 2y + 5 < 2x + 7,
     * generate constraints on x and y that would allow this comparison to be satisfied.
     * It does this by rearranging the equation to the form `ax op c` for every key found, where `a` is the multiplier
     * of one of the keys, and `c` is a constant representing the rest. All variables in this equation are sets.
     * Once we have that form, we divide both sides by `a` to get `x op c/a`, and then we can generate a
     * constraint for x based on the result of that division.
     */
    override fun generateConstraintsFrom(
        other: Variances<T>,
        comparisonOp: ComparisonOp,
        constraints: Constraints
    ): Constraints {
        // Note to self: This almost certainly contains bugs of the 'funky-number-edge-cases' variety.
        // The divide is especially suspect.

        val other = other.into()
        val allKeys = (multipliers.keys + other.multipliers.keys).filter { !it.isConstant() }

        if (allKeys.isEmpty()) {
            return super.generateConstraintsFrom(other, comparisonOp, constraints)
        }

        var constraints = constraints

        for (key in allKeys) {
            val myKeyMultiplier = multipliers[key] ?: LongIndicator.onlyZeroSet()
            val otherKeyMultiplier = other.multipliers[key] ?: LongIndicator.onlyZeroSet()

            // Move all of our key onto the left
            val lhsCoefficient = myKeyMultiplier.subtract(otherKeyMultiplier)

            // Collapse all non-our-key constants into a single value and move them to the right.
            val collapsedLhsBeforeMove =
                NumberVariances(ind, multipliers.filter { it.key != key })
                    .collapseWithoutLimits(constraints)
            val collapsedRhsBeforeMove =
                NumberVariances(ind, other.multipliers.filter { it.key != key })
                    .collapseWithoutLimits(constraints)

            val rhsConstant = collapsedRhsBeforeMove.subtract(collapsedLhsBeforeMove)

            if (lhsCoefficient.isZero()) {
                // The key has cancelled itself out, this is now an all-or-nothing situation:
                // either the constraint is met, or it isn't.
                // The equation at this point looks like `0x op constant`
                // So we can just check the constant against zero.
                val meetsConstraint = LongIndicator.onlyZeroSet().comparisonOperation(rhsConstant, comparisonOp)
                constraints = when (meetsConstraint) {
                    BooleanSet.EITHER, BooleanSet.TRUE -> constraints.withConstraint(key, key.ind.newFullSet())
                    BooleanSet.FALSE, BooleanSet.NEITHER -> constraints.withConstraint(key, key.ind.newEmptySet())
                }
            } else {
                val shouldFlip = lhsCoefficient.comparisonOperation(LongIndicator.onlyZeroSet(), ComparisonOp.LESS_THAN)
                val rhs = rhsConstant.divide(lhsCoefficient)
                val constraint = when (shouldFlip) {
                    BooleanSet.TRUE -> rhs.getSetSatisfying(comparisonOp.flip())
                    BooleanSet.FALSE -> rhs.getSetSatisfying(comparisonOp)
                    BooleanSet.EITHER -> rhs.getSetSatisfying(comparisonOp)
                        .union(rhs.getSetSatisfying(comparisonOp.flip()))

                    BooleanSet.NEITHER -> throw IllegalStateException("Condition is neither true nor false!")
                }

                // I'm slightly unsure about this cast.
                constraints = constraints.withConstraint(key, constraint.clampCast(key.ind)!!)
            }
        }

        return constraints
    }
}