package com.oberdiah.deepcomplexity.staticAnalysis.constrainedSets

import com.oberdiah.deepcomplexity.context.EvaluationKey
import com.oberdiah.deepcomplexity.context.HeapMarker
import com.oberdiah.deepcomplexity.staticAnalysis.CanBeCast
import com.oberdiah.deepcomplexity.staticAnalysis.Indicator
import com.oberdiah.deepcomplexity.staticAnalysis.sets.ISet
import com.oberdiah.deepcomplexity.staticAnalysis.variances.Variances
import org.jetbrains.kotlin.analysis.utils.collections.mapToSet

/**
 * This is the set of possible values an expression can take, with their constraints.
 *
 * For example, after the code
 * ```
 * int x = 0;
 * if (a * 2 > 5 && b < 10) {
 *     x = 5;
 * }
 * ```
 * x would be a BundleSet with the following bundles:
 * [
 *     {bundle: {0}, constraints: {a > 5/2, b < 10}},
 *     {bundle: {5}, constraints: {a <= 5/2, b >= 10}}
 * ]
 *
 * Now, when an operation is performed between two BundleSets we effectively do an O(n^2) operation,
 * running each bundle against each other bundle.
 *
 * NOTE: The bundle's values are not necessarily mutually exclusive and should be considered
 * OR'd together. Take, for example,
 * ```
 * x = 0;
 * if (a > 5 || (a > 10 && b > 15)) {
 *      x = 5;
 * }
 * ```
 * x would be a BundleSet with the following bundles:
 * [
 *     {bundle: {5}, constraints: {a > 5}},
 *     {bundle: {5}, constraints: {a > 10, b > 15}},
 *     {bundle: {0}, constraints: {a <= 5, a <= 10}} // note that this would simplify
 *     {bundle: {0}, constraints: {a <= 5, b <= 15}}
 * ]
 *
 * A bundle with no variances is fine; it indicates there are no possible values for the expression.
 */
@ConsistentCopyVisibility
data class Bundle<T : Any> private constructor(
    override val ind: Indicator<T>,
    private val variances: Set<ConstrainedVariances<T>>
) : CanBeCast<T> {
    init {
        require(variances.size < 50) {
            "Bundle has far too many variances: ${variances.size} ($variances)"
        }
    }

    companion object {
        fun <T : Any> unconstrainedConstant(a: T): Bundle<T> =
            unconstrained(Indicator.fromValue(a).newConstantSet(a).toConstVariance())

        fun <T : Any> unconstrained(bundle: Variances<T>): Bundle<T> {
            return Bundle(
                bundle.ind,
                setOf(
                    ConstrainedVariances.new(bundle, Constraints.completelyUnconstrained())
                )
            )
        }

        @Suppress("unused")
        fun <T : Any> unreachable(ind: Indicator<T>): Bundle<T> = Bundle(ind, emptySet())
    }

    @ConsistentCopyVisibility
    data class ConstrainedVariances<T : Any> private constructor(
        val variances: Variances<T>,
        val constraints: Constraints
    ) {
        companion object {
            fun <T : Any> new(variances: Variances<T>, constraints: Constraints): ConstrainedVariances<T> {
                return ConstrainedVariances(variances, constraints)
            }

            fun <T : Any> fromKeyAndSet(evalKey: EvaluationKey, allowedValues: ISet<T>): ConstrainedVariances<T> {
                require(evalKey.ind == allowedValues.ind) {
                    "Indicator mismatch between evaluation key and allowed values ($evalKey vs $allowedValues)"
                }
                val newConstraints = Constraints.completelyUnconstrained().withConstraint(evalKey, allowedValues)
                return ConstrainedVariances(evalKey.asVariance().coerceTo(allowedValues.ind), newConstraints)
            }
        }

        fun andAlsoWithConstraints(constraints: Constraints): ConstrainedVariances<T> =
            ConstrainedVariances(variances, constraints.and(this.constraints))

        override fun toString(): String {
            return toDebugString()
        }

        fun toDebugString(): String {
            if (constraints.isUnconstrained()) {
                return variances.toDebugString(constraints)
            }
            val varsTracking = variances.varsTracking().filter { !it.isAutogenerated() }
            val constraintsToPrint = constraints.constraints.entries.filter { !varsTracking.contains(it.key) }

            if (constraintsToPrint.isEmpty()) {
                return "(${variances.toDebugString(constraints)})"
            }

            val variancesStr = variances.toDebugString(Constraints.completelyUnconstrained())
            val constraintsStr = constraintsToPrint.joinToString { "${it.key}[${it.value}]" }
            return "(${variancesStr} | $constraintsStr)"
        }
    }

    fun isEmpty(): Boolean {
        return variances.isEmpty() || variances.all { it.constraints.unreachable }
    }

    override fun toString(): String {
        return toDebugString()
    }

    /**
     * Might return additional information beyond simply what the set contains.
     */
    fun toDebugString(): String {
        if (variances.size == 1) {
            return variances.first().toDebugString()
        }

        return variances.joinToString {
            it.toDebugString()
        }
    }

    fun union(other: Bundle<T>): Bundle<T> {
        return Bundle(ind, variances.union(other.variances))
    }

    @Suppress("unused")
    fun <Q : Any> unaryMapAndUnion(
        newInd: Indicator<Q>,
        op: (Variances<T>, Constraints) -> Bundle<Q>
    ): Bundle<Q> =
        Bundle(newInd, variances.flatMap { oldVariances ->
            op(oldVariances.variances, oldVariances.constraints).variances.mapNotNull { newVariances ->
                val newConstraints = oldVariances.constraints.and(newVariances.constraints)

                if (newConstraints.unreachable) {
                    null
                } else {
                    if (oldVariances.constraints.isUnconstrained()) {
                        // No need to combine the constraints as we've got nothing new to add,
                        // we can just return the new bundle
                        newVariances
                    } else {
                        ConstrainedVariances.new(newVariances.variances, newConstraints)
                    }
                }
            }
        }.toSet())

    fun <Q : Any> binaryMapToList(
        other: Bundle<T>,
        op: (Variances<T>, Variances<T>, Constraints) -> Q
    ): List<Q> {
        val listOut = mutableListOf<Q>()
        for (myBundle in variances) {
            for (otherBundle in other.variances) {
                val newConstraints = myBundle.constraints.and(otherBundle.constraints)
                if (newConstraints.unreachable) continue
                listOut.add(op(myBundle.variances, otherBundle.variances, newConstraints))
            }
        }
        return listOut
    }

    fun unaryMapSameType(op: (Variances<T>, Constraints) -> Variances<T>): Bundle<T> = unaryMap(ind, op)

    fun <Q : Any> unaryMap(newInd: Indicator<Q>, op: (Variances<T>, Constraints) -> Variances<Q>): Bundle<Q> {
        // Note, I've never had the need to do the complicated ExprKey tracking here, so
        // it doesn't exist. If you find you need it, you should be able to add it similar
        // to how [binaryMap] does.
        return Bundle(newInd, variances.mapToSet {
            ConstrainedVariances.new(op(it.variances, it.constraints), it.constraints)
        })
    }

    fun binaryMapSameType(
        other: Bundle<T>,
        op: (Variances<T>, Variances<T>, Constraints) -> ConstrainedVariances<T>
    ): Bundle<T> = binaryMap(ind, other, op)

    fun <Q : Any> binaryMap(
        newInd: Indicator<Q>,
        other: Bundle<T>,
        op: (Variances<T>, Variances<T>, Constraints) -> ConstrainedVariances<Q>
    ): Bundle<Q> {
        require(ind == other.ind) {
            "Cannot perform binary operation on bundles with different indicators: $ind vs ${other.ind}"
        }

        val newBundles = mutableSetOf<ConstrainedVariances<Q>>()
        for (myBundle in variances) {
            for (otherBundle in other.variances) {
                val newConstraints = myBundle.constraints.and(otherBundle.constraints)
                if (newConstraints.unreachable) continue
                newBundles.add(op(myBundle.variances, otherBundle.variances, newConstraints))
            }
        }

        return Bundle(newInd, newBundles)
    }

    fun constrainWith(constraints: ConstraintsOrPile): Bundle<T> {
        return Bundle(ind, variances.flatMap { bundle ->
            constraints.pile.flatMap { constraint ->
                val newConstraints = bundle.constraints.and(constraint)
                if (newConstraints.unreachable) {
                    emptyList()
                } else {
                    listOf(ConstrainedVariances.new(bundle.variances, newConstraints))
                }
            }
        }.toSet())
    }

    /**
     * Collapses the full set of bundles into a single set.
     *
     * @return A single bundle representing the collapsed state of the current bundle set.
     */
    fun collapse(): ISet<T> {
        if (variances.isEmpty()) {
            return ind.newEmptySet()
        }

        return variances.fold(ind.newEmptySet()) { acc, bundle ->
            acc.union(bundle.variances.collapse(bundle.constraints))
        }
    }

    override fun <Q : Any> tryCastTo(newInd: Indicator<Q>): Bundle<Q>? {
        if (newInd == ind) {
            // Safety: The indicators are the same, so the cast is valid
            @Suppress("UNCHECKED_CAST")
            return this as Bundle<Q>
        }

        val cast = Bundle(
            newInd, variances.mapToSet {
                ConstrainedVariances.new(
                    it.variances.attemptHardCastTo(newInd, it.constraints) ?: return null,
                    it.constraints
                )
            }
        )
        return cast
    }

    override fun coerceToNumbers(): Bundle<out Number> = super.coerceToNumbers() as Bundle<out Number>
    override fun coerceToObject(): Bundle<HeapMarker> = super.coerceToObject() as Bundle<HeapMarker>
    override fun <Q : Any> coerceTo(newInd: Indicator<Q>): Bundle<Q> = super.coerceTo(newInd) as Bundle<Q>
    override fun <Q : Any> castTo(newInd: Indicator<Q>): Bundle<Q> = super.castTo(newInd) as Bundle<Q>
}